/**
 * Declares CSS side-effect imports (`import '../../global.css'`).
 *
 * TypeScript 6 reports TS2882 for a side-effect import with no declaration.
 * The file is consumed by NativeWind at bundle time and has no runtime exports,
 * so an empty module is the accurate shape — not `any`.
 *
 * This lives outside `nativewind-env.d.ts` because that file is generated by
 * react-native-css and documents that it should not be edited.
 */
declare module '*.css' {}
